uploads = []
outputs = []

[[generated]]
id = "l64AaMeV29o1KdzsRj7RL"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1QnvYOJagJB_igBFn2PYk"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
